[package]
name = "electrs"
version = "0.9.9"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"
build = "build.rs"

[features]
default = ["metrics", "redb-feat"]
heed-feat = ["heed"]
lmdb-rkv-feat= ["lmdb-rkv"]
metrics = ["prometheus", "tiny_http"]
metrics_process = ["prometheus/process"]
# Needs edition 2021. Override toolchain version: https://rust-lang.github.io/rustup/overrides.html
redb-feat = ["redb"]
rocksdb-feat = ["electrs-rocksdb"]
sled-feat = ["sled"]

[package.metadata.configure_me]
spec = "internal/config_specification.toml"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.29.1", features = ["serde", "rand"] }
bitcoincore-rpc = "0.16"
configure_me = "0.4"
crossbeam-channel = "0.5"
dirs-next = "2.0"
env_logger = "0.9"
fs_extra = "1.2"
heed = { version = "0.11.0", optional = true }
lmdb-rkv = { version = "0.14.0", optional = true }
log = "0.4"
parking_lot = "0.11"
prometheus = { version = "0.13", optional = true }
rayon = "1.5"
redb = { version = "0.5.0", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.3"
sled = { version = "0.34.7", features = ["compression"], optional = true }
tiny_http = { version = "0.9", optional = true }

[dependencies.electrs-rocksdb]
# Workaround the following issues:
# - https://github.com/romanz/electrs/issues/403 (support building on ARM 32-bit)
# - https://github.com/romanz/electrs/issues/469 (dynamic linking on Debian 11)
version = "0.15.0-e2"
default-features = false
# ZSTD is used for data compression
# Snappy is only for checking old DB
features = ["zstd", "snappy"]
optional = true

[build-dependencies]
configure_me_codegen = "0.4.2"

[dev-dependencies]
tempfile = "3.3"
