name: electrs

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # once a day

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-redb:
    name: Build redb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.61.0
          profile: minimal
          components: rustfmt, clippy

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: fmt
          args: --all -- --check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: build
          args: --locked --all --no-default-features --features metrics --features redb-feat

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: test
          args: --locked --all --no-default-features --features redb-feat

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: clippy
          args: -- -D warnings

      - name: Install cargo-bloat
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: install
          args: cargo-bloat

      - name: Run cargo-bloat
        uses: actions-rs/cargo@v1
        with:
          toolchain: 1.61.0
          command: bloat
          args: --locked --all --no-default-features --features redb-feat --release --crates --time

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-args:
          [
            --features rocksdb-feat,
            --features metrics --features rocksdb-feat,
            --features metrics --features metrics_process --features rocksdb-feat
          ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --all --no-default-features ${{ matrix.build-args }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --all --no-default-features --features rocksdb-feat

  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -f Dockerfile.ci . --rm -t electrs:tests
      - name: Test
        run: docker run -v $PWD/contrib/:/contrib -v $PWD/tests/:/tests --rm electrs:tests bash /tests/run.sh
